<clusterfriend-item>
    <article>
        <div>{opts.item.description}</div>
        <div><small>{opts.item.pubDate}</small></div>
    </article>
    <script>
        console.log(this.opts.item);
    </script>
</clusterfriend-item>